name: Ensure migrations run
on:
  pull_request:

jobs:
  test:
    name: Check Migrations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Check migrations
        run: bash .github/check_migrations.sh
